global:
  scrape_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'service'
    scrape_interval: 5s
    scheme: https
    static_configs:
      - targets: ['service:8001']
    tls_config:
      insecure_skip_verify: true
